### ISSUE TITLE
SparkGenericCatalog not support Iceberg

### ISSUE THREAD

**Issue by melin** [apache/paimon#2292]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.5.0-incubating

### Compute Engine

```
        val spark = SparkSession.builder()
          .master("local")
          .enableHiveSupport()
          .config("spark.serializer", "org.apache.spark.serializer.KryoSerializer")

          .config("spark.sql.extensions", "org.apache.spark.sql.hudi.HoodieSparkSessionExtension,org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions")
          .config("spark.sql.catalog.hudi_catalog", "org.apache.spark.sql.hudi.catalog.HoodieCatalog")

          .config("spark.sql.catalog.iceberg_catalog", "org.apache.iceberg.spark.SparkCatalog")
          .config("spark.sql.catalog.iceberg_catalog", "org.apache.iceberg.spark.SparkSessionCatalog")
          .config("spark.sql.catalog.iceberg_catalog.type", "hive")
          .config("spark.sql.catalog.iceberg_catalog.uri", "thrift://cdh2:9083")

          .config("spark.sql.catalog.hive_metastore", "org.apache.paimon.spark.SparkGenericCatalog")
          .getOrCreate()

        println("hello hudi")
        spark.sql("select * from hive_metastore.bigdata.hudi_sample_1").show
        println("hello paimon")
        spark.sql("select * from hive_metastore.bigdata.paimon_sample").show
        println("hello iceberg")
        spark.sql("select * from hive_metastore.bigdata.iceberg_sample_1").show
```

### Minimal reproduce step

```
hello hudi
+-------------------+--------------------+------------------+----------------------+-----------------+---+----+
|_hoodie_commit_time|_hoodie_commit_seqno|_hoodie_record_key|_hoodie_partition_path|_hoodie_file_name| id|data|
+-------------------+--------------------+------------------+----------------------+-----------------+---+----+
+-------------------+--------------------+------------------+----------------------+-----------------+---+----+

hello paimon
+---+---+
|  k|  v|
+---+---+
+---+---+

hello iceberg
Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1893)
	at org.example.spark.datasource.hudi.PaimonTest1$.main(PaimonTest1.scala:22)
	at org.example.spark.datasource.hudi.PaimonTest1.main(PaimonTest1.scala)
Caused by: java.util.concurrent.ExecutionException: org.apache.spark.sql.AnalysisException: iceberg is not a valid Spark SQL Data Source.
	at org.sparkproject.guava.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:306)
	at org.sparkproject.guava.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:293)
	at org.sparkproject.guava.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
	at org.sparkproject.guava.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:135)
	at org.sparkproject.guava.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2410)
	at org.sparkproject.guava.cache.LocalCache$Segment.loadSync(LocalCache.java:2380)
	at org.sparkproject.guava.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2342)
	at org.sparkproject.guava.cache.LocalCache$Segment.get(LocalCache.java:2257)
	at org.sparkproject.guava.cache.LocalCache.get(LocalCache.java:4000)
	at org.sparkproject.guava.cache.LocalCache$LocalManualCache.get(LocalCache.java:4789)
	at org.apache.spark.sql.catalyst.catalog.SessionCatalog.getCachedPlan(SessionCatalog.scala:209)
	at org.apache.spark.sql.execution.datasources.FindDataSourceTable.org$apache$spark$sql$execution$datasources$FindDataSourceTable$$readDataSourceTable(DataSourceStrategy.scala:245)
	at org.apache.spark.sql.execution.datasources.FindDataSourceTable$$anonfun$apply$2.applyOrElse(DataSourceStrategy.scala:285)
	at org.apache.spark.sql.execution.datasources.FindDataSourceTable$$anonfun$apply$2.applyOrElse(DataSourceStrategy.scala:275)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsDownWithPruning$2(AnalysisHelper.scala:170)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:104)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsDownWithPruning$1(AnalysisHelper.scala:170)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:323)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsDownWithPruning(AnalysisHelper.scala:168)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsDownWithPruning$(AnalysisHelper.scala:164)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsDownWithPruning$4(AnalysisHelper.scala:175)
	at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren(TreeNode.scala:1249)
	at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren$(TreeNode.scala:1248)
	at org.apache.spark.sql.catalyst.plans.logical.SubqueryAlias.mapChildren(basicLogicalOperators.scala:1631)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsDownWithPruning$1(AnalysisHelper.scala:175)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:323)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsDownWithPruning(AnalysisHelper.scala:168)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsDownWithPruning$(AnalysisHelper.scala:164)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsDownWithPruning$4(AnalysisHelper.scala:175)
	at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren(TreeNode.scala:1249)
	at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren$(TreeNode.scala:1248)
	at org.apache.spark.sql.catalyst.plans.logical.Project.mapChildren(basicLogicalOperators.scala:69)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsDownWithPruning$1(AnalysisHelper.scala:175)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:323)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsDownWithPruning(AnalysisHelper.scala:168)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsDownWithPruning$(AnalysisHelper.scala:164)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsWithPruning(AnalysisHelper.scala:99)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsWithPruning$(AnalysisHelper.scala:96)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperators(AnalysisHelper.scala:76)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperators$(AnalysisHelper.scala:75)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperators(LogicalPlan.scala:31)
	at org.apache.spark.sql.execution.datasources.FindDataSourceTable.apply(DataSourceStrategy.scala:275)
	at org.apache.spark.sql.execution.datasources.FindDataSourceTable.apply(DataSourceStrategy.scala:239)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$2(RuleExecutor.scala:222)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:91)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1(RuleExecutor.scala:219)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1$adapted(RuleExecutor.scala:211)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:211)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.org$apache$spark$sql$catalyst$analysis$Analyzer$$executeSameContext(Analyzer.scala:228)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$execute$1(Analyzer.scala:224)
	at org.apache.spark.sql.catalyst.analysis.AnalysisContext$.withNewAnalysisContext(Analyzer.scala:173)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:224)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:188)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$executeAndTrack$1(RuleExecutor.scala:182)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:88)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.executeAndTrack(RuleExecutor.scala:182)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:209)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:330)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:208)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$analyzed$1(QueryExecution.scala:76)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:202)
	at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:526)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:202)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:827)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:201)
	at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:76)
	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:74)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:66)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:97)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:827)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:95)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:640)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:827)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:630)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:671)
	at org.example.spark.datasource.hudi.PaimonTest1$$anon$1.run(PaimonTest1.scala:45)
	at org.example.spark.datasource.hudi.PaimonTest1$$anon$1.run(PaimonTest1.scala:22)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1875)
	... 2 more
Caused by: org.apache.spark.sql.AnalysisException: iceberg is not a valid Spark SQL Data Source.
	at org.apache.spark.sql.errors.QueryCompilationErrors$.invalidDataSourceError(QueryCompilationErrors.scala:1457)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:420)
	at org.apache.spark.sql.execution.datasources.FindDataSourceTable.$anonfun$readDataSourceTable$1(DataSourceStrategy.scala:257)
	at org.sparkproject.guava.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4792)
	at org.sparkproject.guava.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3599)
	at org.sparkproject.guava.cache.LocalCache$Segment.loadSync(LocalCache.java:2379)
	... 84 more
```

添加spark-iceberg-bundle
![image](https://github.com/apache/incubator-paimon/assets/1145830/b5ac1b81-978a-47b6-88bc-482ec1f1d1f7)

### What doesn't meet your expectations?

Catalog hive_metastore supports access to different types of paimon, hudi, iceberg table

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Zouxxyy** [comment]
@melin How can you use SparkGenericCatalog to create iceberg table?

**Comment by Zouxxyy** [comment]
> > @melin How can you use SparkGenericCatalog to create iceberg table?
> 
> <img alt="image" width="728" src="https://user-images.githubusercontent.com/1145830/281783918-1b31c16a-c4e8-4da9-8886-1db89680e350.png">
> 创建hudi table 是正常的

hudi 表的创建不强依赖catalog

**Comment by Paper-plane123** [comment]
讲个笑话：高考考场门口穿旗袍的不一定都是美女，偶尔也有大叔。

**Comment by tcodehuber** [comment]
Is it OK for the two tables(one is iceberg format, another is paimon format) in the same catalog name if using `org.apache.paimon.spark.SparkGenericCatalog` now? @Zouxxyy

**Comment by Zouxxyy** [comment]
> Is it OK for the two tables(one is iceberg format, another is paimon format) in the same catalog name if using `org.apache.paimon.spark.SparkGenericCatalog` now? @Zouxxyy

No, this is by design, just like iceberg's sessioncatalog cannot load the paimon table

**Comment by tcodehuber** [comment]
> > Is it OK for the two tables(one is iceberg format, another is paimon format) in the same catalog name if using `org.apache.paimon.spark.SparkGenericCatalog` now? @Zouxxyy
> 
> No, this is by design, just like iceberg's sessioncatalog cannot load the paimon table

Got it, thanks for your kind reply.

**Comment by tcodehuber** [comment]
> 自定义了SparkSessionCatalog， 同时支持iceberg和paimon，遇到一个问题。 iceberg 和paimon 的ProcedureCatalog 接口都有相同名方法 loadProcedure， 无法同时实现。只能有一个数据湖支持 Procedure。
> 
> [@Zouxxyy](https://github.com/Zouxxyy) [@tcodehuber](https://github.com/tcodehuber)
> 
> ```
> public class SuperiorSparkSessionCatalog
>         implements StagingTableCatalog, ProcedureCatalog, SupportsNamespaces, HasIcebergCatalog, SupportsFunctions, WithPaimonCatalog, CatalogExtension {
> 
>     private static final Logger LOG = LoggerFactory.getLogger(SuperiorSparkSessionCatalog.class);
> 
>     protected String catalogName;
> 
>     // iceberg
>     private SparkSessionCatalog icebergCatalog;
> 
>     // paimon
>     private SparkCatalog paimonCatalog = null;
> 
>     @Override
>     public String name() {
>         return catalogName;
>     }
> 
>     @Override
>     public final void initialize(String name, CaseInsensitiveStringMap options) {
>         this.catalogName = name;
> 
>         icebergCatalog = new SparkSessionCatalog();
>         icebergCatalog.initialize(name, options);
> 
>         // paimon
>         SparkSession sparkSession = SparkSession.active();
>         SessionState sessionState = sparkSession.sessionState();
>         Configuration hadoopConf = sessionState.newHadoopConf();
>         this.paimonCatalog = new SparkCatalog();
>         CaseInsensitiveStringMap newOptions =
>                 autoFillConfigurations(options, sessionState.conf(), hadoopConf);
>         this.paimonCatalog.initialize(name, newOptions);
>     }
> 
> 
>     @Override
>     @SuppressWarnings("unchecked")
>     public void setDelegateCatalog(CatalogPlugin sparkSessionCatalog) {
>         icebergCatalog.setDelegateCatalog(sparkSessionCatalog);
>     }
> 
>     @Override
>     public Catalog paimonCatalog() {
>         return this.paimonCatalog.paimonCatalog();
>     }
> 
>     @Override
>     public org.apache.iceberg.catalog.Catalog icebergCatalog() {
>         return icebergCatalog.icebergCatalog();
>     }
> 
>     @Override
>     public Procedure loadProcedure(Identifier identifier) throws NoSuchProcedureException {
>         return icebergCatalog.loadProcedure(identifier);
>     }
> 
>     @Override
>     public StagedTable stageCreate(Identifier ident, StructType structType, Transform[] transforms, Map<String, String> properties) throws TableAlreadyExistsException, NoSuchNamespaceException {
>         return icebergCatalog.stageCreate(ident, structType, transforms, properties);
>     }
> 
>     @Override
>     public StagedTable stageReplace(Identifier ident, StructType structType, Transform[] transforms, Map<String, String> properties) throws NoSuchNamespaceException, NoSuchTableException {
>         return icebergCatalog.stageReplace(ident, structType, transforms, properties);
>     }
> 
>     @Override
>     public StagedTable stageCreateOrReplace(Identifier ident, StructType structType, Transform[] transforms, Map<String, String> properties) throws NoSuchNamespaceException {
>         return icebergCatalog.stageCreateOrReplace(ident, structType, transforms, properties);
>     }
> 
>     @Override
>     public String[][] listNamespaces() throws NoSuchNamespaceException {
>         return icebergCatalog.listNamespaces();
>     }
> 
>     @Override
>     public String[][] listNamespaces(String[] namespace) throws NoSuchNamespaceException {
>         return icebergCatalog.listNamespaces(namespace);
>     }
> 
>     @Override
>     public Map<String, String> loadNamespaceMetadata(String[] namespace) throws NoSuchNamespaceException {
>         return icebergCatalog.loadNamespaceMetadata(namespace);
>     }
> 
>     @Override
>     public void createNamespace(String[] namespace, Map<String, String> properties) throws NamespaceAlreadyExistsException {
>         icebergCatalog.createNamespace(namespace, properties);
>     }
> 
>     @Override
>     public void alterNamespace(String[] namespace, NamespaceChange... namespaceChanges) throws NoSuchNamespaceException {
>         icebergCatalog.alterNamespace(namespace, namespaceChanges);
>     }
> 
>     @Override
>     public boolean dropNamespace(String[] namespace, boolean cascade) throws NoSuchNamespaceException, NonEmptyNamespaceException {
>         return icebergCatalog.dropNamespace(namespace, cascade);
>     }
> 
>     @Override
>     public Identifier[] listTables(String[] namespace) throws NoSuchNamespaceException {
>         return icebergCatalog.listTables(namespace);
>     }
> 
>     @Override
>     public Table loadTable(Identifier ident) throws NoSuchTableException {
>         try {
>             return this.paimonCatalog.loadTable(ident);
>         } catch (NoSuchTableException e) {
>             return icebergCatalog.loadTable(ident);
>         }
>     }
> 
>     @Override
>     public Table createTable(Identifier ident, StructType structType, Transform[] transforms, Map<String, String> properties) throws TableAlreadyExistsException, NoSuchNamespaceException {
>         String provider = properties.get(TableCatalog.PROP_PROVIDER);
>         if (usePaimon(provider)) {
>             return paimonCatalog.createTable(ident, structType, transforms, properties);
>         } else {
>             return icebergCatalog.createTable(ident, structType, transforms, properties);
>         }
>     }
> 
>     @Override
>     public Table alterTable(Identifier ident, TableChange... changes) throws NoSuchTableException {
>         if (paimonCatalog.tableExists(ident)) {
>             return paimonCatalog.alterTable(ident, changes);
>         } else {
>             return icebergCatalog.alterTable(ident, changes);
>         }
>     }
> 
>     @Override
>     public boolean dropTable(Identifier ident) {
>         return icebergCatalog.dropTable(ident) || paimonCatalog.dropTable(ident);
>     }
> 
>     @Override
>     public void renameTable(Identifier from, Identifier to) throws NoSuchTableException, TableAlreadyExistsException {
>         if (paimonCatalog.tableExists(from)) {
>             paimonCatalog.renameTable(from, to);
>         } else {
>             icebergCatalog.renameTable(from, to);
>         }
>     }
> 
>     //----------------------------- paimon -----------------------------
>     public boolean usePaimon(String provider) {
>         return provider == null || SparkSource.NAME().equalsIgnoreCase(provider);
>     }
> 
>     private CaseInsensitiveStringMap autoFillConfigurations(
>             CaseInsensitiveStringMap options, SQLConf sqlConf, Configuration hadoopConf) {
>         Map<String, String> newOptions = new HashMap<>(options.asCaseSensitiveMap());
>         fillAliyunConfigurations(newOptions, hadoopConf);
>         fillCommonConfigurations(newOptions, sqlConf);
> 
>         // if spark is case-insensitive, set allow upper case to catalog
>         newOptions.put("allow-upper-case", "true");
>         return new CaseInsensitiveStringMap(newOptions);
>     }
> 
>     private void fillAliyunConfigurations(Map<String, String> options, Configuration hadoopConf) {
>         if (!options.containsKey(METASTORE.key())) {
>             // In Alibaba Cloud EMR, `hive.metastore.type` has two types: DLF or LOCAL, for DLF, we
>             // set `metastore` to dlf, for LOCAL, do nothing.
>             String aliyunEMRHiveMetastoreType = hadoopConf.get("hive.metastore.type", null);
>             if ("dlf".equalsIgnoreCase(aliyunEMRHiveMetastoreType)) {
>                 options.put(METASTORE.key(), "dlf");
>             }
>         }
>     }
> 
>     private void fillCommonConfigurations(Map<String, String> options, SQLConf sqlConf) {
>         if (!options.containsKey(WAREHOUSE.key())) {
>             String warehouse = sqlConf.warehousePath();
>             options.put(WAREHOUSE.key(), warehouse);
>         }
>         if (!options.containsKey(METASTORE.key())) {
>             String metastore = sqlConf.getConf(StaticSQLConf.CATALOG_IMPLEMENTATION());
>             if (HiveCatalogOptions.IDENTIFIER.equals(metastore)) {
>                 options.put(METASTORE.key(), metastore);
>             }
>         }
>         String sessionCatalogDefaultDatabase = SQLConfUtils.defaultDatabase(sqlConf);
>         if (options.containsKey(DEFAULT_DATABASE.key())) {
>             String userDefineDefaultDatabase = options.get(DEFAULT_DATABASE.key());
>             if (!userDefineDefaultDatabase.equals(sessionCatalogDefaultDatabase)) {
>                 LOG.warn(
>                         String.format(
>                                 "The current spark version does not support configuring default database, switch database to %s",
>                                 sessionCatalogDefaultDatabase));
>                 options.put(DEFAULT_DATABASE.key(), sessionCatalogDefaultDatabase);
>             }
>         } else {
>             options.put(DEFAULT_DATABASE.key(), sessionCatalogDefaultDatabase);
>         }
>     }
> }
> ```
@melin 
I think it's ok for your usage. Procedures can only be used by admins in general. Unifying catalog is convenient for the end users because of the seamless switch (Don't need change the ETL sql snippet).  If we want use paimon's procedure, the admin can register a separate catalog such as paimon_catalog, which will take smart work for us.
