### ISSUE TITLE
[Bug] tez query paimon error

### ISSUE THREAD

**Issue by gitfortian** [apache/paimon#3802]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

0.8.1

### Compute Engine

hive on tez

### Minimal reproduce step

select 
count(1)
from 
test.test_log l left join test.test_log_detail a
on l.uuid = a.uuid and l.dt=a.dt and l.hour=a.hour
where l.topic='test001' and l.hour='14';

### What doesn't meet your expectations?

INFO  : Total jobs = 1
INFO  : Launching Job 1 out of 1
INFO  : Starting task [Stage-1:MAPRED] in parallel
ERROR : FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.tez.TezTask. Vertex failed, vertexName=Map 6, vertexId=vertex_1721421013305_0508_1_03, diagnostics=[Vertex vertex_1721421013305_0508_1_03 [Map 6] killed/failed due to:ROOT_INPUT_INIT_FAILURE, Vertex Input: a initializer failed, vertex=vertex_1721421013305_0508_1_03 [Map 6], java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:659)
        at java.util.ArrayList.get(ArrayList.java:435)
        at org.apache.paimon.hive.SearchArgumentToPredicateConverter.convertLeaf(SearchArgumentToPredicateConverter.java:163)
        at org.apache.paimon.hive.SearchArgumentToPredicateConverter.convertTree(SearchArgumentToPredicateConverter.java:124)
        at org.apache.paimon.hive.SearchArgumentToPredicateConverter.convert(SearchArgumentToPredicateConverter.java:91)
        at org.apache.paimon.hive.utils.HiveUtils.createPredicate(HiveUtils.java:89)
        at org.apache.paimon.hive.utils.HiveSplitGenerator.generateSplits(HiveSplitGenerator.java:54)
        at org.apache.paimon.hive.mapred.PaimonInputFormat.getSplits(PaimonInputFormat.java:45)
        at org.apache.hadoop.hive.ql.io.HiveInputFormat.addSplitsForGroup(HiveInputFormat.java:519)
        at org.apache.hadoop.hive.ql.io.HiveInputFormat.getSplits(HiveInputFormat.java:765)
        at org.apache.hadoop.hive.ql.exec.tez.HiveSplitGenerator.initialize(HiveSplitGenerator.java:243)
        at org.apache.tez.dag.app.dag.RootInputInitializerManager$InputInitializerCallable$1.run(RootInputInitializerManager.java:281)
        at org.apache.tez.dag.app.dag.RootInputInitializerManager$InputInitializerCallable$1.run(RootInputInitializerManager.java:272)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878)
        at org.apache.tez.dag.app.dag.RootInputInitializerManager$InputInitializerCallable.call(RootInputInitializerManager.java:272)
        at org.apache.tez.dag.app.dag.RootInputInitializerManager$InputInitializerCallable.call(RootInputInitializerManager.java:256)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
]Vertex killed, vertexName=Reducer 3, vertexId=vertex_1721421013305_0508_1_05, diagnostics=[Vertex received Kill in INITED state., Vertex vertex_1721421013305_0508_1_05 [Reducer 3] killed/failed due to:OTHER_VERTEX_FAILURE]Vertex killed, vertexName=Reducer 4, vertexId=vertex_1721421013305_0508_1_02, diagnostics=[Vertex received Kill in INITED state., Vertex vertex_1721421013305_0508_1_02 [Reducer 4] killed/failed due to:OTHER_VERTEX_FAILURE]Vertex killed, vertexName=Reducer 5, vertexId=vertex_1721421013305_0508_1_01, diagnostics=[Vertex received Kill in INITED state., Vertex vertex_1721421013305_0508_1_01 [Reducer 5] killed/failed due to:OTHER_VERTEX_FAILURE]Vertex killed, vertexName=Reducer 2, vertexId=vertex_1721421013305_0508_1_04, diagnostics=[Vertex received Kill in INITED state., Vertex vertex_1721421013305_0508_1_04 [Reducer 2] killed/failed due to:OTHER_VERTEX_FAILURE]Vertex killed, vertexName=Map 1, vertexId=vertex_1721421013305_0508_1_00, diagnostics=[Vertex received Kill in INITED state., Vertex vertex_1721421013305_0508_1_00 [Map 1] killed/failed due to:OTHER_VERTEX_FAILURE]DAG did not succeed due to VERTEX_FAILURE. failedVertices:1 killedVertices:5

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Msimplehub** [comment]
Has this issue been resolved?
