### ISSUE TITLE
[Bug] Rewrite File Index Partition Filter Error

### ISSUE THREAD

**Issue by herefree** [apache/paimon#4004]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

0.9

### Compute Engine

flink1.18

### Minimal reproduce step

CALL sys.rewrite_file_index('default.T','dt=20221208,hh=15')

### What doesn't meet your expectations?

Caused by: org.apache.flink.util.FlinkException: Global failure triggered by OperatorCoordinator for 'Source: index source -> Writer(write-only) : T' (operator cbc357ccb763df2852fee8c4fc7d55f2).
	at org.apache.flink.runtime.operators.coordination.OperatorCoordinatorHolder$LazyInitializedCoordinatorContext.failJob(OperatorCoordinatorHolder.java:651)
	at org.apache.flink.runtime.operators.coordination.RecreateOnResetOperatorCoordinator$QuiesceableContext.failJob(RecreateOnResetOperatorCoordinator.java:259)
	at org.apache.flink.runtime.source.coordinator.SourceCoordinatorContext.failJob(SourceCoordinatorContext.java:432)
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.start(SourceCoordinator.java:236)
	at org.apache.flink.runtime.operators.coordination.RecreateOnResetOperatorCoordinator$DeferrableCoordinator.applyCall(RecreateOnResetOperatorCoordinator.java:343)
	at org.apache.flink.runtime.operators.coordination.RecreateOnResetOperatorCoordinator.start(RecreateOnResetOperatorCoordinator.java:72)
	at org.apache.flink.runtime.operators.coordination.OperatorCoordinatorHolder.start(OperatorCoordinatorHolder.java:204)
	at org.apache.flink.runtime.scheduler.DefaultOperatorCoordinatorHandler.startOperatorCoordinators(DefaultOperatorCoordinatorHandler.java:173)
	at org.apache.flink.runtime.scheduler.DefaultOperatorCoordinatorHandler.registerAndStartNewCoordinators(DefaultOperatorCoordinatorHandler.java:167)
	at org.apache.flink.runtime.scheduler.adaptivebatch.AdaptiveBatchScheduler.initializeOperatorCoordinatorsFor(AdaptiveBatchScheduler.java:834)
	at org.apache.flink.runtime.scheduler.adaptivebatch.AdaptiveBatchScheduler.updateTopology(AdaptiveBatchScheduler.java:826)
	at org.apache.flink.runtime.scheduler.adaptivebatch.AdaptiveBatchScheduler.initializeVerticesIfPossible(AdaptiveBatchScheduler.java:622)
	at org.apache.flink.runtime.scheduler.adaptivebatch.AdaptiveBatchScheduler.lambda$startSchedulingInternal$2(AdaptiveBatchScheduler.java:256)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	... 26 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at org.apache.paimon.memory.MemorySegmentUtils.getLongMultiSegments(MemorySegmentUtils.java:774)
	at org.apache.paimon.memory.MemorySegmentUtils.getLong(MemorySegmentUtils.java:764)
	at org.apache.paimon.data.BinaryArray.getLong(BinaryArray.java:157)
	at org.apache.paimon.predicate.LeafPredicate.test(LeafPredicate.java:102)
	at org.apache.paimon.predicate.And.test(And.java:55)
	at org.apache.paimon.predicate.CompoundPredicate.test(CompoundPredicate.java:59)
	at org.apache.paimon.partition.PartitionPredicate$DefaultPartitionPredicate.test(PartitionPredicate.java:102)
	at org.apache.paimon.operation.AbstractFileStoreScan.filterManifestFileMeta(AbstractFileStoreScan.java:449)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.apache.paimon.operation.AbstractFileStoreScan.readAndMergeFileEntries(AbstractFileStoreScan.java:372)
	at org.apache.paimon.operation.AbstractFileStoreScan.doPlan(AbstractFileStoreScan.java:289)
	at org.apache.paimon.operation.AbstractFileStoreScan.plan(AbstractFileStoreScan.java:225)
	at org.apache.paimon.flink.source.RewriteFileIndexSource.createEnumerator(RewriteFileIndexSource.java:79)
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.start(SourceCoordinator.java:232)
	... 38 more

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by kyzheng196** [comment]
Hi, can you assign this issue to me? Many thanks!

**Comment by kyzheng196** [comment]
The original parametesr from `RewriteFileIndexProcedure` to Flink source code don't contain a partition field. This example has additional partition field parameters of dt and hh, so an error occurred.
I think `flink-table-common` and `flink-table-api` need to be modified to rewrite file index with partitions, but that's not paimon's job. Perhaps the input can be changed?
cc @JingsongLi
