### ISSUE TITLE
[core] Support `schema_id` push down for `$schemas` to improve performance

### ISSUE THREAD

**Issue by liyubin117** [apache/paimon#4093]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Motivation

We have many tables that have undergone multiple table changes, and the number of schema files is particularly large. In particular, querying a table with more than 3,000 schema files takes half an hour, we surely need to make a performance optimization.

### Solution

Modify SchemasTable

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by liyubin117** [comment]
`SchemaManager.listAll` always triggered.
```
at java.io.BufferedReader.readLine(BufferedReader.java:389) ~[?:1.8.0_362]
	at org.apache.paimon.fs.FileIO.readFileUtf8(FileIO.java:198) ~[paimon-flink-1.16-0.8-20240130.001921-3.jar:0.8-SNAPSHOT]
	at org.apache.paimon.schema.SchemaManager.schema(SchemaManager.java:462) ~[paimon-flink-1.16-0.8-20240130.001921-3.jar:0.8-SNAPSHOT]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) [?:1.8.0_362]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) [?:1.8.0_362]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) [?:1.8.0_362]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) [?:1.8.0_362]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) [?:1.8.0_362]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:1.8.0_362]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) [?:1.8.0_362]
	at org.apache.paimon.schema.SchemaManager.listAll(SchemaManager.java:105) [paimon-flink-1.16-0.8-20240130.001921-3.jar:0.8-SNAPSHOT]
	at org.apache.paimon.table.system.SchemasTable$SchemasRead.createReader(SchemasTable.java:203) [paimon-flink-1.16-0.8-20240130.001921-3.jar:0.8-SNAPSHOT]
```
