### ISSUE TITLE
[Bug] Write paimon table with  hive engine by MR got exeception

### ISSUE THREAD

**Issue by FrommyMind** [apache/paimon#4537]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

0.9

### Compute Engine

hive: 2.1-cdh-6.3-1

### Minimal reproduce step

create paimon table in beeline
```sql
SET hive.metastore.warehouse.dir=/user/hive/warehouse;

CREATE TABLE hive_test_table(
    a INT COMMENT 'The a field',
    b STRING COMMENT 'The b field'
)
STORED BY 'org.apache.paimon.hive.PaimonStorageHandler';
```

after that, try insert data
```sql
insert into hive_test_table values (3, 'paimon');
```

### What doesn't meet your expectations?

MapReduce failed with bellow error.

```
2024-11-17 22:11:46,830 INFO [main] org.apache.hadoop.hive.ql.exec.TableScanOperator: Initializing operator TS[0]
2024-11-17 22:11:46,830 INFO [main] org.apache.hadoop.hive.ql.exec.SelectOperator: Initializing operator SEL[1]
2024-11-17 22:11:47,196 INFO [main] org.apache.hadoop.hive.ql.exec.SelectOperator: SELECT struct<tmp_values_col1:string,tmp_values_col2:string>
2024-11-17 22:11:47,203 INFO [main] org.apache.hadoop.hive.ql.exec.FileSinkOperator: Initializing operator FS[3]
2024-11-17 22:11:47,204 INFO [main] org.apache.hadoop.conf.Configuration.deprecation: mapred.task.id is deprecated. Instead, use mapreduce.task.attempt.id
2024-11-17 22:11:47,621 INFO [main] org.apache.hadoop.hive.ql.exec.FileSinkOperator: Using serializer : org.apache.paimon.hive.PaimonSerDe@6ede46f6 and formatter : org.apache.paimon.hive.mapred.PaimonOutputFormat@66273da0
2024-11-17 22:11:47,621 INFO [main] org.apache.hadoop.conf.Configuration.deprecation: mapred.healthChecker.script.timeout is deprecated. Instead, use mapreduce.tasktracker.healthchecker.script.timeout
2024-11-17 22:11:47,634 INFO [main] org.apache.hadoop.hive.ql.exec.FileSinkOperator: New Final Path: FS hdfs://cdh01.daniel.com:8020/user/hive/warehouse/default.db/_tmp.hive_test_table/000000_0
2024-11-17 22:11:47,781 INFO [main] org.apache.hadoop.hive.ql.exec.FileSinkOperator: FS[3]: records written - 1
2024-11-17 22:11:47,913 INFO [main] org.apache.hadoop.io.compress.CodecPool: Got brand-new compressor [.zstd]
2024-11-17 22:11:48,249 INFO [main] org.apache.hadoop.hive.ql.exec.MapOperator: MAP[0]: records read - 1
2024-11-17 22:11:48,249 INFO [main] org.apache.hadoop.hive.ql.exec.MapOperator: MAP[0]: Total records read - 1. abort - false
2024-11-17 22:11:48,249 INFO [main] org.apache.hadoop.hive.ql.exec.MapOperator: DESERIALIZE_ERRORS:0, RECORDS_IN:1, 
2024-11-17 22:11:48,250 INFO [main] org.apache.hadoop.hive.ql.exec.FileSinkOperator: FS[3]: records written - 1
2024-11-17 22:11:48,250 INFO [main] org.apache.hadoop.hive.ql.exec.FileSinkOperator: TOTAL_TABLE_ROWS_WRITTEN:1, RECORDS_OUT_1_default.hive_test_table:1, 
2024-11-17 22:11:48,272 INFO [main] org.apache.hadoop.mapred.Task: Task:attempt_1731851152753_0005_m_000000_0 is done. And is in the process of committing
2024-11-17 22:11:48,276 INFO [main] org.apache.hadoop.mapred.Task: Task attempt_1731851152753_0005_m_000000_0 is allowed to commit now
2024-11-17 22:11:48,357 ERROR [main] org.apache.hadoop.mapred.YarnChild: Error running child : java.lang.UnsatisfiedLinkError: com.github.luben.zstd.ZstdOutputStreamNoFinalizer.recommendedCOutSize()J
	at com.github.luben.zstd.ZstdOutputStreamNoFinalizer.recommendedCOutSize(Native Method)
	at com.github.luben.zstd.ZstdOutputStreamNoFinalizer.<clinit>(ZstdOutputStreamNoFinalizer.java:30)
	at com.github.luben.zstd.RecyclingBufferPool.<clinit>(RecyclingBufferPool.java:17)
	at org.apache.paimon.shade.org.apache.parquet.hadoop.codec.ZstandardCodec.createOutputStream(ZstandardCodec.java:107)
	at org.apache.paimon.shade.org.apache.parquet.hadoop.codec.ZstandardCodec.createOutputStream(ZstandardCodec.java:100)
	at org.apache.paimon.shade.org.apache.parquet.hadoop.CodecFactory$HeapBytesCompressor.compress(CodecFactory.java:176)
	at org.apache.paimon.shade.org.apache.parquet.hadoop.ColumnChunkPageWriteStore$ColumnChunkPageWriter.writePage(ColumnChunkPageWriteStore.java:168)
	at org.apache.paimon.shade.org.apache.parquet.column.impl.ColumnWriterV1.writePage(ColumnWriterV1.java:59)
	at org.apache.paimon.shade.org.apache.parquet.column.impl.ColumnWriterBase.writePage(ColumnWriterBase.java:389)
	at org.apache.paimon.shade.org.apache.parquet.column.impl.ColumnWriteStoreBase.flush(ColumnWriteStoreBase.java:186)
	at org.apache.paimon.shade.org.apache.parquet.column.impl.ColumnWriteStoreV1.flush(ColumnWriteStoreV1.java:29)
	at org.apache.paimon.shade.org.apache.parquet.hadoop.InternalParquetRecordWriter.flushRowGroupToStore(InternalParquetRecordWriter.java:185)
	at org.apache.paimon.shade.org.apache.parquet.hadoop.InternalParquetRecordWriter.close(InternalParquetRecordWriter.java:124)
	at org.apache.paimon.shade.org.apache.parquet.hadoop.ParquetWriter.close(ParquetWriter.java:112)
	at org.apache.paimon.format.parquet.writer.ParquetBulkWriter.close(ParquetBulkWriter.java:52)
	at org.apache.paimon.io.SingleFileWriter.close(SingleFileWriter.java:170)
	at org.apache.paimon.io.RowDataFileWriter.close(RowDataFileWriter.java:104)
	at org.apache.paimon.io.RollingFileWriter.closeCurrentWriter(RollingFileWriter.java:131)
	at org.apache.paimon.io.RollingFileWriter.close(RollingFileWriter.java:168)
	at org.apache.paimon.append.AppendOnlyWriter$DirectSinkWriter.flush(AppendOnlyWriter.java:418)
	at org.apache.paimon.append.AppendOnlyWriter.flush(AppendOnlyWriter.java:219)
	at org.apache.paimon.append.AppendOnlyWriter.prepareCommit(AppendOnlyWriter.java:207)
	at org.apache.paimon.operation.AbstractFileStoreWrite.prepareCommit(AbstractFileStoreWrite.java:210)
	at org.apache.paimon.operation.MemoryFileStoreWrite.prepareCommit(MemoryFileStoreWrite.java:152)
	at org.apache.paimon.table.sink.TableWriteImpl.prepareCommit(TableWriteImpl.java:253)
	at org.apache.paimon.table.sink.TableWriteImpl.prepareCommit(TableWriteImpl.java:260)
	at org.apache.paimon.hive.mapred.PaimonOutputCommitter.commitTask(PaimonOutputCommitter.java:95)
	at org.apache.hadoop.mapred.OutputCommitter.commitTask(OutputCommitter.java:343)
	at org.apache.hadoop.mapred.Task.commit(Task.java:1341)
	at org.apache.hadoop.mapred.Task.done(Task.java:1185)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:351)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:174)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1875)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:168)

2024-11-17 22:11:48,460 INFO [main] org.apache.hadoop.metrics2.impl.MetricsSystemImpl: Stopping MapTask metrics system...
2024-11-17 22:11:48,460 INFO [main] org.apache.hadoop.metrics2.impl.MetricsSystemImpl: MapTask metrics system stopped.
2024-11-17 22:11:48,461 INFO [main] org.apache.hadoop.metrics2.impl.MetricsSystemImpl: MapTask metrics system shutdown complete.
```

### Anything else?

I checked if my cluster supports zstd compression:
Use the following command to run MR job
```shell
hadoop jar /opt/cloudera/parcels/CDH/jars/hadoop-mapreduce-examples*.jar wordcount -Dmapreduce.map.output.compress.codec=org.apache.hadoop.io.compress.ZStandardCodec -Dmapreduce.map.output.compress=true -Dmapreduce.output.fileoutputformat.compress=true -Dmapreduce.output.fileoutputformat.compress.codec=org.apache.hadoop.io.compress.ZStandardCodec wcin wcout-zst
```
The job ran successfully.

a part of that log.
```log
2024-11-17 22:07:43,023 INFO [main] org.apache.hadoop.conf.Configuration.deprecation: session.id is deprecated. Instead, use dfs.metrics.session-id
2024-11-17 22:07:43,410 INFO [main] org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter: File Output Committer Algorithm version is 2
2024-11-17 22:07:43,410 INFO [main] org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter: FileOutputCommitter skip cleanup _temporary folders under output directory:false, ignore cleanup failures: false
2024-11-17 22:07:43,421 INFO [main] org.apache.hadoop.mapred.Task:  Using ResourceCalculatorProcessTree : [ ]
2024-11-17 22:07:43,565 INFO [main] org.apache.hadoop.mapred.MapTask: Processing split: hdfs://cdh01.daniel.com:8020/user/hive/wcin/yum.log:0+0
2024-11-17 22:07:43,672 INFO [main] org.apache.hadoop.mapred.MapTask: (EQUATOR) 0 kvi 67108860(268435440)
2024-11-17 22:07:43,672 INFO [main] org.apache.hadoop.mapred.MapTask: mapreduce.task.io.sort.mb: 256
2024-11-17 22:07:43,672 INFO [main] org.apache.hadoop.mapred.MapTask: soft limit at 214748368
2024-11-17 22:07:43,672 INFO [main] org.apache.hadoop.mapred.MapTask: bufstart = 0; bufvoid = 268435456
2024-11-17 22:07:43,672 INFO [main] org.apache.hadoop.mapred.MapTask: kvstart = 67108860; length = 16777216
2024-11-17 22:07:43,679 INFO [main] org.apache.hadoop.mapred.MapTask: Map output collector class = org.apache.hadoop.mapred.MapTask$MapOutputBuffer
2024-11-17 22:07:43,696 INFO [main] org.apache.hadoop.mapred.MapTask: Starting flush of map output
2024-11-17 22:07:43,715 INFO [main] org.apache.hadoop.io.compress.CodecPool: Got brand-new compressor [.zst]
2024-11-17 22:07:43,739 INFO [main] org.apache.hadoop.mapred.Task: Task:attempt_1731851152753_0004_m_000000_0 is done. And is in the process of committing
2024-11-17 22:07:43,770 INFO [main] org.apache.hadoop.mapred.Task: Task 'attempt_1731851152753_0004_m_000000_0' done.
2024-11-17 22:07:43,778 INFO [main] org.apache.hadoop.mapred.Task: Final Counters for attempt_1731851152753_0004_m_000000_0: Counters: 29
	File System Counters
		FILE: Number of bytes read=0
		FILE: Number of bytes written=220970
		FILE: Number of read operations=0
		FILE: Number of large read operations=0
		FILE: Number of write operations=0
		HDFS: Number of bytes read=116
		HDFS: Number of bytes written=0
		HDFS: Number of read operations=3
		HDFS: Number of large read operations=0
		HDFS: Number of write operations=0
		HDFS: Number of bytes read erasure-coded=0
	Map-Reduce Framework
		Map input records=0
		Map output records=0
		Map output bytes=0
		Map output materialized bytes=90
		Input split bytes=116
		Combine input records=0
		Combine output records=0
		Spilled Records=0
		Failed Shuffles=0
		Merged Map outputs=0
		GC time elapsed (ms)=41
		CPU time spent (ms)=430
		Physical memory (bytes) snapshot=482156544
		Virtual memory (bytes) snapshot=2589884416
		Total committed heap usage (bytes)=480247808
		Peak Map Physical memory (bytes)=482156544
		Peak Map Virtual memory (bytes)=2589884416
	File Input Format Counters 
		Bytes Read=0
2024-11-17 22:07:43,879 INFO [main] org.apache.hadoop.metrics2.impl.MetricsSystemImpl: Stopping MapTask metrics system...
2024-11-17 22:07:43,879 INFO [main] org.apache.hadoop.metrics2.impl.MetricsSystemImpl: MapTask metrics system stopped.
2024-11-17 22:07:43,879 INFO [main] org.apache.hadoop.metrics2.impl.MetricsSystemImpl: MapTask metrics system shutdown complete.
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ChrisKyrie** [comment]
I encountered the same problem and solved it by upgrading the zstd-jni version to zstd-jni-1.5.5-11 
https://github.com/apache/paimon/issues/4531

**Comment by FrommyMind** [comment]
I tied with below steps:

1. put zstd-jni-1.5.5-11.jar under hive auxlib path.
2. restart hiveserver2
3. insert data to paimon table.

the problem still there.

**Comment by FrommyMind** [comment]
@ChrisKyrie , Thank you qulickly answer.

my cluster is CHD6.3.2 , the zstd-jni not under hive/lib.  it under mr/lib
![image](https://github.com/user-attachments/assets/3e16a119-d3f9-491c-90a1-101d489b5a84)

I don't think it's a good idea to remove the zstd-jni-1.3.8.jar on all yarn nodemanager nodes.

I'm not sure if this will cause other problems.

**Comment by ChrisKyrie** [comment]
The essence of the problem is that zstd-jni-1.3.8-1.jar does not contain the class ZstdOutputStreamNoFinalizer，and paimon require zstd-jni-1.5.5-11.jar

**Comment by FrommyMind** [comment]
Update:

I finally discovered that MR utilizes `/user/yarn/mapreduce/mr-framework/3.0.0-cdh6.3.2-mr-framework.tar.gz` on HDFS as the location for all dependency jars, so I updated this file to include zstd-jni-1.5.5-1.jar. After making this change, the insert statement executed successfully! Additionally, I ran the original MR job with zstd compression, and it worked perfectly as well.

Perhaps we should consider adding more test cases to ensure that there are no issues with the original MR job. However, for now, everything seems fine to me.

**Comment by FrommyMind** [comment]
It turns out that I set the wrong value for "hive.metastore.warehouse.dir".

**Comment by yangjf2019** [comment]
I think this is a package conflict issue, can you please find out the lower version of the jar package where this class is located using the following command? 
1.  yarn classpath
2. jar -vtf *.jar | grep 'com.github.luben.zstd.ZstdOutputStreamNoFinalizer'
3. delete zstd-jni-*.jar
4. put zstd-jni-1.5.5-11.jar under hadoop classpath
5. restart hiveserver2
6. insert data to paimon table.

**Comment by yangjf2019** [comment]
I would also suggest lowering the log level and turning on debug to get more clue information to help troubleshoot the problem.

**Comment by bing0109** [comment]
@FrommyMind 大佬，你好，请教个问题，我用的hive版本应该和你的差不多 , hive-2.1.1-cdh6.3.1, 请问你有没有遇到以下问题没？
我是在flink-sql-client中建paimon表（'metastore.partitioned-table' = 'true' 同步分区数据到hivemetestore），通过flink从kafka读取ogg-json数据，然后写到paimon表的，但在flink运行1-2h的样子之后就会失败，看日志像是flink要修改paimon表分区时hive不支持报错(报错日志如下)，如果我修改paimon表设置'metastore.partitioned-table' = 'false'不同步分区数据到hive, flink任务就能正常恢复，创建对应的hive外部表又查不到数据(无报错)

报错内容：java.lang.NoSuchMethodError: org.apache.hadoop.hive.metastore.IMetaStoreClient.alter_partition 

具体日志如下：
```` 
2025-03-28 11:29:53,518 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph       [] - Writer : paimon_test_ogg -> Global Committer : paimon_test_ogg -> end: Writer (1/1) (9097ca9872f9d8c1a563314b90452db1_c16a96e78194357634f51bcfea60f56a_0_0) switched from RUNNING to FAILED on container_1742182751832_102612_01_000004 @ 10.xx.xx.xx (dataPort=28456).
java.lang.NoSuchMethodError: org.apache.hadoop.hive.metastore.IMetaStoreClient.alter_partition(Ljava/lang/String;Ljava/lang/String;Lorg/apache/hadoop/hive/metastore/api/Partition;)V
	at org.apache.paimon.hive.HiveMetastoreClient.lambda$alterPartition$5(HiveMetastoreClient.java:140) ~[paimon-flink-1.18-1.0.1.jar:1.0.1]
	at org.apache.paimon.client.ClientPool$ClientPoolImpl.lambda$execute$0(ClientPool.java:80) ~[paimon-flink-1.18-1.0.1.jar:1.0.1]
	at org.apache.paimon.client.ClientPool$ClientPoolImpl.run(ClientPool.java:68) ~[paimon-flink-1.18-1.0.1.jar:1.0.1]
	at org.apache.paimon.client.ClientPool$ClientPoolImpl.execute(ClientPool.java:77) ~[paimon-flink-1.18-1.0.1.jar:1.0.1]
	at org.apache.paimon.hive.pool.CachedClientPool.execute(CachedClientPool.java:139) ~[paimon-flink-1.18-1.0.1.jar:1.0.1]
	at org.apache.paimon.hive.HiveMetastoreClient.alterPartition(HiveMetastoreClient.java:138) ~[paimon-flink-1.18-1.0.1.jar:1.0.1]
	at org.apache.paimon.flink.sink.partition.PartitionStatisticsReporter.report(PartitionStatisticsReporter.java:88) ~[paimon-flink-1.18-1.0.1.jar:1.0.1]
	at org.apache.paimon.flink.sink.partition.ReportPartStatsListener.notifyCommittable(ReportPartStatsListener.java:111) ~[paimon-flink-1.18-1.0.1.jar:1.0.1]
	at org.apache.paimon.flink.sink.partition.PartitionListeners.notifyCommittable(PartitionListeners.java:42) ~[paimon-flink-1.18-1.0.1.jar:1.0.1]
	at org.apache.paimon.flink.sink.StoreCommitter.commit(StoreCommitter.java:113) ~[paimon-flink-1.18-1.0.1.jar:1.0.1]
	at org.apache.paimon.flink.sink.CommitterOperator.commitUpToCheckpoint(CommitterOperator.java:210) ~[paimon-flink-1.18-1.0.1.jar:1.0.1]
	at org.apache.paimon.flink.sink.CommitterOperator.notifyCheckpointComplete(CommitterOperator.java:187) ~[paimon-flink-1.18-1.0.1.jar:1.0.1]
	at org.apache.flink.streaming.runtime.tasks.StreamOperatorWrapper.notifyCheckpointComplete(StreamOperatorWrapper.java:104) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.notifyCheckpointComplete(RegularOperatorChain.java:145) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.tasks.SubtaskCheckpointCoordinatorImpl.notifyCheckpoint(SubtaskCheckpointCoordinatorImpl.java:468) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.tasks.SubtaskCheckpointCoordinatorImpl.notifyCheckpointComplete(SubtaskCheckpointCoordinatorImpl.java:401) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.notifyCheckpointComplete(StreamTask.java:1449) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$notifyCheckpointCompleteAsync$17(StreamTask.java:1390) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$notifyCheckpointOperation$20(StreamTask.java:1429) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.runThrowing(StreamTaskActionExecutor.java:50) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.tasks.mailbox.Mail.run(Mail.java:90) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMail(MailboxProcessor.java:398) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.processMailsWhenDefaultActionUnavailable(MailboxProcessor.java:367) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.processMail(MailboxProcessor.java:352) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:229) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:858) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:807) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:953) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:932) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:746) ~[flink-dist-1.18.1.jar:1.18.1]
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:562) ~[flink-dist-1.18.1.jar:1.18.1]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_181]

```

**Comment by hz-git** [comment]
@FrommyMind @yangjf2019 
两位大佬，我从github Paimon1.2中看到依赖的zstd-jni的包是1.5.5-11的版本，但CDH6.3.[1-2]自带的是zstd-jni-1.3.8-1.jar的版本，请问除了您上面解决这个zstd-jni问题的时候，是在将各个NodeManager节点的自带的zstd-jni-1.3.8-1.jar以及/user/yarn/mapreduce/mr-framework/3.0.0-cdh6.3.2-mr-framework.tar.gz中包含的zstd-jni-1.3.8-1.jar都删除后，重新将zstd-jni-1.5.5的jar放入/user/yarn/mapreduce/mr-framework/3.0.0-cdh6.3.2-mr-framework.tar.gz中，才执行成功的吗？
